#include "includeh.h"
extern SHOOTING_STATE SHOOT_STATE ;




void shooting_FSM_task(void *pvParameters)
{
	while(1)
	{
	 
	if(SWD>1500)
	{
	Cylinder_PUSH;
	}
	if(SWD<1500)
	{
	Cylinder_BACK;
	}
	if(1200<SWB&&SWB<1700)
	{
		SHOOT_STATE=STOP_SHOOTING;	
	}
//	else
//	SHOOT_STATE=STOP_SHOOTING;		
//×´Ì¬ÇÐ»»
	
switch(SHOOT_STATE)
{
	case SHOOTING_1://Ò»ºÅ
    MIT_DRIVER_REAL_INFO[0].TARGET_SPEED=18;
    MIT_DRIVER_REAL_INFO[1].TARGET_SPEED=18;
	  MIT_DRIVER_REAL_INFO[2].TARGET_SPEED=-18;
	  MIT_DRIVER_REAL_INFO[3].TARGET_SPEED=18;
	
		M3508_CHASSIS_MOTOR_REAL_INFO[3].TARGET_ANGLE=-3000;		
		break;
	case SHOOTING_2:
	 MIT_DRIVER_REAL_INFO[0].TARGET_SPEED=38;
    MIT_DRIVER_REAL_INFO[1].TARGET_SPEED=38;
	  MIT_DRIVER_REAL_INFO[2].TARGET_SPEED=-38;
	  MIT_DRIVER_REAL_INFO[3].TARGET_SPEED=38;
		M3508_CHASSIS_MOTOR_REAL_INFO[3].TARGET_ANGLE=-7200;		
		break;
	case SHOOTING_3:
		MIT_DRIVER_REAL_INFO[0].TARGET_SPEED=50;
    MIT_DRIVER_REAL_INFO[1].TARGET_SPEED=50;
	  MIT_DRIVER_REAL_INFO[2].TARGET_SPEED=-50;
	  MIT_DRIVER_REAL_INFO[3].TARGET_SPEED=50;
		M3508_CHASSIS_MOTOR_REAL_INFO[3].TARGET_ANGLE=-7300;		
		break;
	case SHOOTING_4:
		break;
	case SHOOTING_5:
		break;
	case SHOOTING_6:
		break;
	case STOP_SHOOTING:
		 MIT_DRIVER_REAL_INFO[0].TARGET_SPEED=0;
    MIT_DRIVER_REAL_INFO[1].TARGET_SPEED=0;
	  MIT_DRIVER_REAL_INFO[2].TARGET_SPEED=0;
	  MIT_DRIVER_REAL_INFO[3].TARGET_SPEED=0;

		break;
	
  default:
		break;
}
vTaskDelay(5);
}

}	
